"""change

Revision ID: 105f3c3ba9e4
Revises: 15cfc9cbc4cb
Create Date: 2023-12-17 14:55:02.067604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105f3c3ba9e4'
down_revision: Union[str, None] = '15cfc9cbc4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('desk_user_id_fkey', 'desk', type_='foreignkey')
    op.create_foreign_key(None, 'desk', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_type_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_desk_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'task_type', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'desk', ['desk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_type_user_id_fkey', 'task_type', type_='foreignkey')
    op.create_foreign_key(None, 'task_type', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_type', type_='foreignkey')
    op.create_foreign_key('task_type_user_id_fkey', 'task_type', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_desk_id_fkey', 'task', 'desk', ['desk_id'], ['id'])
    op.create_foreign_key('task_type_id_fkey', 'task', 'task_type', ['type_id'], ['id'])
    op.drop_constraint(None, 'desk', type_='foreignkey')
    op.create_foreign_key('desk_user_id_fkey', 'desk', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
